### ISSUE TITLE
关于数据库连接问题

### ISSUE THREAD

**Issue by jweboy** [csbun/thal#2]
> function upsertUser(userObj) {
>
>  const DB_URL = 'mongodb://localhost/thal';
>  if (mongoose.connection.readyState == 0) {
>    mongoose.connect(DB_URL);
>  }
> ……
> }

upsertUser这个函数在读取user变量并插入每一条的user的时候，每次调用都会去连接一次数据库，这里是否可以优化为脚本连通数据库之后，每次map插入到库中，最后在脚本停止之后断开数据库，并browser.close()

**Comment by csbun** [comment]
并没有每次插入都链接一次：

```js
  const DB_URL = 'mongodb://localhost/thal';
  if (mongoose.connection.readyState == 0) {
    mongoose.connect(DB_URL);
  }
```

这里 `if (mongoose.connection.readyState == 0)` 语句已经判断了链接状态。

```js
  for (let h = 1; h <= numPages; h++) {
    // 跳转到指定页码
    await page.goto(`${searchUrl}&p=${h}`);
    // ...
    users.map(({username, email}) => {
      // 保存用户信息
      upsertUser(/* ... */);
    });
  }

  browser.close();
```

这里可以看到是遍历了所有页面（`for` 循环），每个页面逐一保存 user（`users.map()`），上述结束后才执行一次 `browser.close()`。

**Comment by jweboy** [comment]
好的，理解力，感谢解答～
