### ISSUE TITLE
卡在了await page.screenshot({path:"screenshots/github.png"})

### ISSUE THREAD

**Issue by eruca** [csbun/thal#4]
无法运行下去
node 8.5.0
puppeteer 0.10.2

**Comment by csbun** [comment]
请问有错误信息么？

**Comment by rosasspain** [comment]
我就是想问这个可以用来做什么啊？

**Comment by csbun** [comment]
@eruca 可能是没有创建 screenshots 文件夹，可以手动创建后试试。
@lovejsgirl 自动化测试、爬虫等等都可以。
