### ISSUE TITLE
登陆不成功

### ISSUE THREAD

**Issue by losymear** [csbun/thal#5]
总是按钮下面的' Create an account.'被点击到，这是什么原因呢

**Comment by csbun** [comment]
__sign in__ 和 __Create an account__ 是两个不同的按钮，selector 也不一样。
你可以尝试在你的浏览器中看看 `document.querySelectorAll('#login > form > div.auth-form-body.mt-3 > input.btn.btn-primary.btn-block')` 是否选中了 __sign in__ 按钮
