### ISSUE TITLE
只能遍历100页是 GitHub API 限制了

### ISSUE THREAD

**Issue by wilkice** [csbun/thal#9]
> 译者注：我爬了100页并没有被阻止。从 101 页开始就变成了 404 页面，或许通过页面下方的页码进行遍历会更合理

每个搜索只能最多得到 1000 个结果，所以从页面下方遍历也只能提取到100页。详见 https://developer.github.com/v3/search/

> The Search API helps you search for the specific item you want to find. For example, you can find a user or a specific file in a repository. Think of it the way you think of performing a search on Google. It's designed to help you find the one result you're looking for (or maybe the few results you're looking for). Just like searching on Google, you sometimes want to see a few pages of search results so that you can find the item that best meets your needs. To satisfy that need, the GitHub Search API provides **up to 1,000 results** for each search.

**Comment by csbun** [comment]
我们爬取的是页面，和开放 API 没有关系
